language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-cms-component' ]; then cd .. && eval "mv $currentfolder generator-cms-component" && cd generator-cms-component; fi

